name : MAEv2
## Modèle plus gros :2,6M de paramètres. Dimension de l'encodeur/décodeur x2 par rapport à la v1
patch_size : 12 # le patch size doit diviser window_size
masking_ratio : 0.5
encoder_embed_dim : 128
encoder_n_attn_heads : 4 ## sous-espaces de dimension 64 
encoder_n_blocks : 12
decoder_embed_dim : 64
decoder_n_attn_heads : 4 ## sous-espaces de dimension 16 
decoder_n_blocks : 4
expansion_factor : 4 ## projection MLP de dimension 512
dropout_rate : 0.0

