name : miniMAE
## Plus petit MAE pour test pipeline

patch_size : 12
masking_ratio : 0.5
encoder_embed_dim : 32
encoder_n_attn_heads : 1
encoder_n_blocks : 1
decoder_embed_dim : 16
decoder_n_attn_heads : 1
decoder_n_blocks : 1
expansion_factor : 1
dropout_rate : 0.0