name : pretrain

channel_weights:
  dt: 0.0
  cosM: 0.0
  sinM: 0.0
  cosRAAN: 0.0
  sinRAAN: 0.0
  cosARGP: 0.0
  sinARGP: 0.0

  ## Focalisation. sma et sma_diff a parite
  sma: 1.5
  sma_diff: 0.55
  i_continue: 0.56
  ecc: 0.22
  bstar: 0.19
