constellations:
  - {name_pattern: "STARLINK", country: "US" }
  - {name_pattern: "MOLNIYA", country: "CIS" }
  - {name_pattern: "ONEWEB", country: "" }
  - {name_pattern: "GSAT", country: "" }
  - {name_pattern: "GALILEO", country: "" }
  - {name_pattern: "", country: "PRC"}



data_range: {start: 2026-01-01, end: 2026-03-01}


features: [semimajor_axis, eccentricity, inclination, raan, arg_of_perigee, mean_anomaly, mean_motion, bstar]
# raan peut être potentiellement retiré pour le ml car a une dynamique déterministe, cf Cipollone 2025



