### ce fichier config assemble les groupes model / data / train. 
## Hydra fusionne ces morceaux en un seul cfg
defaults : 
  - model : naive_baseline
  - data : splid
  - train : defaults
  - _self_

