## Config Hydra : assemble les groupes model / data / train

defaults : 
  - task : localizer
  - model : cnn_lstm1
  - data : splid
  - train : default 
  - _self_ 

seed : 42

hydra : 
  run :
   dir : ${hydra:runtime.cwd}/outputs/ml/${task.name}/${now:%Y-%m-%d_%H-%M-%S}

  
